#+title: filepaths

Inspired by [[https://github.com/vindarel/cl-str][str]], this library offers modern and consistent filepath manipulation
for Common Lisp.

It addresses three main issues found with the status quo, namely:

- Centrality: Functionality is spread across the standard library and =uiop=.
- Completeness: A number of common operations found in newer languages are missing entirely.
- Clarity: Function names are often unintuitive.

The =filepaths= library solves these issues by offering functions commonly found
elsewhere while naming them what you'd generally expect them to be.

Intuitive concatenation:

#+begin_src lisp
(filepaths:join "/home/you/code" "common-lisp" "hello.lisp")
#+end_src

#+RESULTS:
: #P"/home/you/code/common-lisp/hello.lisp"

Swapping the extension:

#+begin_src lisp
(filepaths:with-extension #p"/home/you/code/common-lisp/hello.lisp" "txt")
#+end_src

#+RESULTS:
: #P"/home/you/code/common-lisp/hello.txt"

Swapping the directory portion:

#+begin_src lisp
(filepaths:with-parent #p"/home/you/code/common-lisp/hello.lisp" "/tmp")
#+end_src

#+RESULTS:
: #P"/tmp/hello.lisp"

And much more! Note that this library is currently _Unix only_ and doesn't offer
functions for communicating with the filesystem to test if files exist, etc.

* Installation

This library has no external dependencies. It only uses standard library functionality.

* Usage

It is recommended that you import this library with the nickname =path= or =p=.

#+begin_src lisp
(:local-nicknames (:p :filepaths))
#+end_src

** Structural Tests
** Construction
** Component Access
** Conversion
** Conditions

* Further Work

- Windows support
