on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Clone the Project
        uses: actions/checkout@v4

      - name: Install Vend
        uses: fosskers/common-lisp@v0.0.8

      - name: Test
        run: |
          vend test
